### ISSUE TITLE
Enter your Skills (Type a skill and press comma) - input is case sensitive

### ISSUE THREAD

**Issue by rakesh1623** [kindo-tk/job_hunter#1]
# The skill input field is case senstive

***Problem***

The results are not showing up when it is 'Python', but they do show up when it is 'python'.

Input field for skills in case senstive treating 'Python' and 'python' differently.

**Comment by kindo-tk** [comment]
Thanks, buddy for reporting the issue. Fixed the case-sensitive bug. Please check and let me know.
